### ISSUE TITLE
use_state final basic api.

### ISSUE THREAD

**Issue by rebo** [rebo/seed-quickstart-hooks#5]
This issue is to finalise the use_state basic api for storing variables of type T in a component.

To be agreed that the type signature of basic `use_state` will be : 

```rust
fn use_state<T: 'static, F: FnOnce() -> T>(data_fn: F) -> StateAccess<T>
```
This returns a `StateAccess<T>` struct that has the following main methods:

```rust
fn get(&self) -> T;  // for T: Clone types only
fn get_with<F: FnOnce(&T) -> R, R>(self, func: F) -> R; // fallback for non-Clone types
fn update<F: FnOnce(&mut T) -> ()>(self, func: F);
fn set(self, value: T);
```

* The reason for a single accessor return type is so that clone and non clone types can share a use_state api.
* The reason for `get()` being available on Clone types is for convenience. Typical reads will be via `value.get()`.
* `use_state` returns without a clone'd copy of the state also reduce accidental stale state usage.
* `update()` prefered for most mutation due to reducing accidental stale state usage
* `set()` available for convenience. Care to be taken by user to not use a stale value as the argument.
* `get()` and `update()` panic if underlying variable does not exist in the store. If garbage collection story is correctly addressed then this shouldn't happen.
* StateAccess is `Copy` so as to enable easy passing to callbacks.

**Comment by MartinKavik** [comment]
I agree. Very nice summary, we should use it for docs / code comments.

**Comment by rebo** [comment]
Updated this repo both master and inc_comp_state branches to use this new api style.

Closing this issue.
